-- Categories DDL and data seeding (idempotent and safe to re-run)
BEGIN;

-- Create categories table with proper constraints and metadata
CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_categories_code UNIQUE (code),
    CONSTRAINT ck_categories_code_min_len CHECK (char_length(code) >= 2)
);

-- Ensure products.category_id column exists and types match categories.id
ALTER TABLE products
    ADD COLUMN IF NOT EXISTS category_id INTEGER;

-- Ensure FK exists with sane actions (CASCADE on update, RESTRICT on delete)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND tc.table_name = 'products'
          AND tc.constraint_name = 'products_category_id_fkey'
    ) THEN
        ALTER TABLE products
            ADD CONSTRAINT products_category_id_fkey
            FOREIGN KEY (category_id)
            REFERENCES categories(id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;
    END IF;
END $$;

-- Seed base categories (idempotent upsert)
INSERT INTO categories (code, name) VALUES
    ('clothing', 'Clothing'),
    ('shoes', 'Shoes'),
    ('accessories', 'Accessories')
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    updated_at = NOW();

-- Backfill products categories by code mapping (safe if re-run)
UPDATE products
SET category_id = (SELECT id FROM categories WHERE code = 'clothing')
WHERE code IN ('PROD001','PROD004','PROD007');

UPDATE products
SET category_id = (SELECT id FROM categories WHERE code = 'shoes')
WHERE code IN ('PROD002','PROD006');

UPDATE products
SET category_id = (SELECT id FROM categories WHERE code = 'accessories')
WHERE code IN ('PROD003','PROD005','PROD008');

-- Enforce NOT NULL on products.category_id only after data is backfilled
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM products WHERE category_id IS NULL) THEN
        ALTER TABLE products ALTER COLUMN category_id SET NOT NULL;
    END IF;
END $$;

-- Schema documentation
COMMENT ON TABLE categories IS 'Product categories master data';
COMMENT ON COLUMN categories.id IS 'Surrogate primary key';
COMMENT ON COLUMN categories.code IS 'Human-readable unique identifier (e.g., clothing, shoes)';
COMMENT ON COLUMN categories.name IS 'Human-readable category name';
COMMENT ON COLUMN categories.created_at IS 'Row creation timestamp';
COMMENT ON COLUMN categories.updated_at IS 'Row update timestamp';

COMMIT;
